# Generated by Django 2.0.5 on 2019-06-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=30)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('mobile', models.PositiveIntegerField()),
            ],
        ),
    ]
